steps:
  # Set up Go environment and build the Go application
  - name: 'golang:1.21'
    entrypoint: 'bash'
    args: ['-c', 'GOOS=linux GOARCH=amd64 go build -o fermat-linux .']

  # Upload the built application to a Google Cloud Storage bucket
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'fermat-linux', 'docker-compose.yaml', 'gs://swizzle_scripts_$_PROFILE']
    id: upload
tags:
  - fermat
