version: '3.7'

services:
  theia:
    image: codercom/code-server
    environment:
      PASSWORD: password
      SUPER_ADMIN_PASSWORD: password
    volumes:
      - $HOME/code:/home/coder/swizzle-data/code
      - $HOME/.config:/home/coder/swizzle-data/.config
    ports:
      - "8080:8080"
    restart: unless-stopped
  nodemon-server:
    image: node:18
    working_dir: /swizzle-data/code
    environment:
      PORT: 4411
    volumes:
      - $HOME/code:/swizzle-data/code
    command: sh -c "npm install && npx nodemon index.js"
    ports:
      - "4411:4411"
    restart: always
  mongo:
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
