version: '3.7'

services:
  pascal:
    image: us-central1-docker.pkg.dev/swizzle-prod/pascal/pascal:latest
    volumes:
      - $HOME/code:$HOME/code
    ports:
      - "3000:3000"
    restart: unless-stopped
  nodemon-server:
    image: node:18
    working_dir: /swizzle-data/code
    environment:
      SWIZZLE_SUPER_SECRET: ${SWIZZLE_SUPER_SECRET}
      PORT: 4411
    volumes:
      - $HOME/code:/swizzle-data/code
    command: sh -c "npm install && npx nodemon --inspect=0.0.0.0:9229 server.js >> /swizzle-data/code/app.log 2>&1"
    ports: ["4411:4411", "9229:9229"]
    restart: always
  mongo:
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always
volumes:
  mongo-data:
