certificatesResolvers:
  myResolver:
    acme:
      email: swizzle@swizzle.run
      storage: acme.json
      httpChallenge:
        entryPoint: web
http:
  middlewares:
    cors-headers:
      headers:
        accessControlAllowMethods:
          - "GET"
          - "POST"
          - "PUT"
          - "DELETE"
          - "OPTIONS"  # Add this
        accessControlAllowOrigin: "*"
        accessControlAllowHeaders:
          - "Cache-Control"
          - "Content-Type"
          - "Authorization"