version: "3.7"

services:
  pascal:
    init: true
    image: us-central1-docker.pkg.dev/${GCP_PROJECT}/pascal/pascal:latest
    volumes:
      - $HOME/code:/swizzle/code
      - $HOME/.config/gcloud/application_default_credentials.json:/home/root/.config/gcloud/application_default_credentials.json
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /home/root/.config/gcloud/application_default_credentials.json
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    ports:
      - "3000:3000"
    restart: unless-stopped

  backend:
    init: true
    image: node:18.19.0
    working_dir: /swizzle/code
    environment:
      SWIZZLE_SUPER_SECRET: ${SWIZZLE_SUPER_SECRET}
      SWIZZLE_PROJECT_NAME: ${SWIZZLE_PROJECT_NAME}
      SWIZZLE_ENV: test
      GOOGLE_APPLICATION_CREDENTIALS: /home/root/.config/gcloud/application_default_credentials.json
      PORT: 4411
    volumes:
      - $HOME/code/backend:/swizzle/code
      - $HOME/.config/gcloud/application_default_credentials.json:/home/root/.config/gcloud/application_default_credentials.json
    command: sh -c "npm install && npx nodemon --config nodemon.json >> /swizzle/code/server.log 2>&1"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    ports:
      - "4411:4411"
    restart: always

  frontend:
    init: true
    image: node:18.19.0
    working_dir: /swizzle/code
    environment:
      PORT: 4545
      WDS_SOCKET_PORT: 443
    volumes:
      - $HOME/code/frontend:/swizzle/code
    command: sh -c "npm install && npm run start >> /swizzle/code/app.log 2>&1"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    ports:
      - "4545:4545"
    restart: always

  mongo:
    image: mongo:latest
    command:
      - "--bind_ip_all"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: main
    ports:
      - "27017:27017"
    volumes:
      - /mnt/${MONGO_VOLUME_NAME}:/data/db
    logging:
      driver: "json-file"
      options:
        max-size: "20000k"
        max-file: "10"
    restart: always
